/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uwm.infost325;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author zach
 */
public class BasicCryptGUI extends javax.swing.JFrame {

    /**
     * Creates new form BasicCrpytGUI
     */
    //Creates the file chooser objects
    private final JFileChooser sourceLocation;
    private final JFileChooser destLocation;
    
    //Creates the file objects
    public File destFile;
    public File selectedFile;

    public BasicCryptGUI() {
        initComponents();
        
        //Creates the file choosers
        sourceLocation = new JFileChooser();
        destLocation = new JFileChooser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        sourceLoc = new javax.swing.JButton();
        destinationLoc = new javax.swing.JButton();
        sourceFilePathVis = new javax.swing.JTextField();
        destFilePathVis = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        hashFile = new javax.swing.JButton();
        hashVis = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        encryptBtn = new javax.swing.JButton();
        decryptbtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sourceLoc.setText("Source Location");
        sourceLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceLocActionPerformed(evt);
            }
        });

        destinationLoc.setText("Destination Location");
        destinationLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationLocActionPerformed(evt);
            }
        });

        sourceFilePathVis.setEditable(false);
        sourceFilePathVis.setText("Source File Path");
        sourceFilePathVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceFilePathVisActionPerformed(evt);
            }
        });

        destFilePathVis.setEditable(false);
        destFilePathVis.setText("Destination File Path");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sourceLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourceFilePathVis, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destinationLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destFilePathVis))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceFilePathVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destFilePathVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        hashFile.setText("Hash File");
        hashFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashFileActionPerformed(evt);
            }
        });

        hashVis.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hashFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hashVis)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hashFile)
                    .addComponent(hashVis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Program Controls"));
        jPanel1.setToolTipText("");

        encryptBtn.setText("Encrypt");
        encryptBtn.setMaximumSize(new java.awt.Dimension(93, 29));
        encryptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptBtnActionPerformed(evt);
            }
        });

        decryptbtn.setText("Decrypt");
        decryptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptbtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.setMaximumSize(new java.awt.Dimension(93, 29));
        cancelBtn.setMinimumSize(new java.awt.Dimension(93, 29));
        cancelBtn.setPreferredSize(new java.awt.Dimension(93, 29));

        clearBtn.setText("Clear");
        clearBtn.setMaximumSize(new java.awt.Dimension(93, 29));
        clearBtn.setMinimumSize(new java.awt.Dimension(93, 29));
        clearBtn.setPreferredSize(new java.awt.Dimension(93, 29));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        aboutBtn.setText("About");
        aboutBtn.setMaximumSize(new java.awt.Dimension(93, 29));
        aboutBtn.setMinimumSize(new java.awt.Dimension(93, 29));
        aboutBtn.setPreferredSize(new java.awt.Dimension(93, 29));
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(encryptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decryptbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptbtn)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        exitBtn.setText("Exit");
        exitBtn.setMaximumSize(new java.awt.Dimension(93, 29));
        exitBtn.setMinimumSize(new java.awt.Dimension(93, 29));
        exitBtn.setPreferredSize(new java.awt.Dimension(93, 29));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void destinationLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationLocActionPerformed
            //Provides a value for the results of the dialogue box           
        int returnVal = destLocation.showSaveDialog(this);
           
        //Runs conditional if the user selects a destination
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {
                
                //Places the directory in destFile and changes the textbox
                //to the directory path                
                this.destFile = destLocation.getSelectedFile(); 
                destFilePathVis.setText(destFile.toString());
                
            }
    }//GEN-LAST:event_destinationLocActionPerformed

    private void sourceLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceLocActionPerformed
            //Provides a value for the results of the dialogue box
            int returnVal = sourceLocation.showOpenDialog(this);
            
            //Runs conditional if the user selects a file
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {   
                //Places the directory in selectedFile and changes the textbox
                //to the directory path
                this.selectedFile = sourceLocation.getSelectedFile(); 
                sourceFilePathVis.setText(selectedFile.toString());
                
            }
    }//GEN-LAST:event_sourceLocActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        //Exits the program
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
            //Opens the about frame
            JFrame frame = new aboutGUI();
            frame.setTitle("Cryptology About");
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.setVisible(true);
            frame.setResizable(false);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void sourceFilePathVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceFilePathVisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceFilePathVisActionPerformed

    private void encryptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptBtnActionPerformed
        if (selectedFile != null && destFile != null)
        {
        JFrame frame = new JFrame();
        String result = JOptionPane.showInputDialog(frame, "Enter a password using A-Z, a-z, /, + with the last letter A-D and a max length of 22 characters ");
        byte [] passB;
       
            if (result.length() <= 22 && result.length() >= 1) 
            {
                if (result.matches("[A-Za-z0-9/+]+"))
                {
                    char passwordLast = result.charAt(result.length() - 1);

                    if (passwordLast == 'A' || passwordLast == 'B' || passwordLast == 'C')
                    {

                        passB = result.getBytes();
                        System.out.println(passB);
                        //CryptController.encrypt(selectedFile, destFile, (this)passB);
                    }
                    else 
                    {
                    JFrame parent = new JFrame();
                    JOptionPane.showMessageDialog(parent, "The format is incorrect, please enter it again.");
                    }
                }
                else 
                {
                JFrame parent = new JFrame();
                JOptionPane.showMessageDialog(parent, "The format is incorrect, please enter it again.");
                }
            } 
            else 
            {
                JFrame parent = new JFrame();
                JOptionPane.showMessageDialog(parent, "The format is incorrect, please enter it again.");
            }
        }
        else
        {
            JFrame warning = new JFrame();
            JOptionPane.showMessageDialog(warning, "You are missing directories!");
        }
        //http://www.java2s.com/Tutorial/Java/0240__Swing/InputPopUps.htm
        
      
    }//GEN-LAST:event_encryptBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        //Resets text fields
        destFilePathVis.setText("Destination File Path");
        sourceFilePathVis.setText("Source File Path");
        hashVis.setText("");
        
        //Resets File variables
        this.selectedFile = null;
        this.destFile = null;
    }//GEN-LAST:event_clearBtnActionPerformed

    private void decryptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptbtnActionPerformed
    
    if (selectedFile != null && destFile != null)
    {
        JFrame frame = new JFrame();
        String resultD = JOptionPane.showInputDialog(frame, "Enter a password using A-Z, a-z, /, + with the last letter A-D and a max length of 22 characters ");    
        
        if (resultD.length() <= 22 && resultD.length() >= 1) 
        {
            if (resultD.matches("[A-Za-z0-9/+]+"))
            {
                char passwordLast = resultD.charAt(resultD.length() - 1);
                
                if (passwordLast == 'A' || passwordLast == 'B' || passwordLast == 'C')
                {
                    //CryptController.decrypt(selectedFile, destFile, (this)passB);
                }
                else 
                {
                JFrame parent = new JFrame();
                JOptionPane.showMessageDialog(parent, "The format is incorrect, please enter it again.");
                }
            }
            else 
            {
            JFrame parent = new JFrame();
            JOptionPane.showMessageDialog(parent, "The format is incorrect, please enter it again.");
            }
        } 
        else 
        {
            JFrame parent = new JFrame();
            JOptionPane.showMessageDialog(parent, "The format is incorrect, please enter it again.");
        }
    }
    else
    {
            JFrame warning = new JFrame();
            JOptionPane.showMessageDialog(warning, "You are missing directories!");        
    }
        //http://www.java2s.com/Tutorial/Java/0240__Swing/InputPopUps.htm
    }//GEN-LAST:event_decryptbtnActionPerformed

    private void hashFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashFileActionPerformed
        //Hash.
    }//GEN-LAST:event_hashFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCryptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCryptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCryptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCryptGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //Disaplys the GUI
                new BasicCryptGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton decryptbtn;
    private javax.swing.JTextField destFilePathVis;
    private javax.swing.JButton destinationLoc;
    private javax.swing.JButton encryptBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton hashFile;
    private javax.swing.JTextField hashVis;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar progressBar;
    public javax.swing.JTextField sourceFilePathVis;
    private javax.swing.JButton sourceLoc;
    // End of variables declaration//GEN-END:variables
}
